name: Deploy Worker to Cloudflare

# 监听事件：当代码被推送到 main 分支时触发此工作流
on:
  push:
    branches:
      - main
  # 也可以添加 workflow_dispatch 以便手动触发部署
  workflow_dispatch:

# 设置部署权限
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        # 检出代码到 Runner 环境

      - name: Publish Worker
        uses: cloudflare/wrangler-action@v3 
        with:
          # 使用在 GitHub Secrets 中设置的 API Token
          apiToken: ${{ yRy2MMK8rutlpsVG0rD5HMu1EDgLd70OeVNEi4T- }} 
          # 使用 wrangler.toml 文件中的配置进行部署
          command: deploy
          # accountId 是可选的，如果您的 wrangler.toml 中已经配置了 account_id
          # 否则需要在这里或 wrangler.toml 中添加 Cloudflare Account ID

      - name: Deployment Success
        run: echo "Cloudflare Worker 部署成功!"
